[phases.setup]
nixPkgs = ["python311", "git", "bash", "gcc", "libffi", "openssl", "sqlite"]


providers = ['...', 'python']

[phases.install]
cmds = ['pnpm i --frozen-lockfile']

[start]
cmd = 'pnpm railway:start:backend'