# Generated by Django 4.2.7 on 2024-11-01 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('idadmin', models.AutoField(db_column='idAdmin', primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('contrasena', models.TextField()),
            ],
            options={
                'db_table': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('idarchivo', models.AutoField(db_column='idArchivo', primary_key=True, serialize=False)),
                ('archivolink', models.ImageField(blank=True, upload_to='photos/')),
            ],
            options={
                'db_table': 'Archivo',
            },
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('idcv', models.AutoField(primary_key=True, serialize=False)),
                ('cvlink', models.FileField(blank=True, upload_to='cv/')),
            ],
            options={
                'db_table': 'Cv',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('idlocalidad', models.AutoField(db_column='idLocalidad', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'Localidad',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('idprofesion', models.AutoField(db_column='idProfesion', primary_key=True, serialize=False)),
                ('experiencia', models.IntegerField()),
                ('nombre', models.TextField()),
            ],
            options={
                'db_table': 'Profesion',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('idtrabajador', models.AutoField(db_column='idTrabajador', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('uniforme', models.BooleanField(default=False)),
                ('talle', models.TextField()),
                ('dni', models.IntegerField(db_column='DNI')),
                ('email', models.TextField()),
                ('numtel', models.IntegerField(db_column='numTel')),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estadotrabajo', models.TextField(db_column='estadoTrabajo')),
                ('estadocontrato', models.TextField(db_column='estadoContrato')),
                ('idarchivo', models.ForeignKey(db_column='idArchivo', on_delete=django.db.models.deletion.CASCADE, to='app.archivo')),
                ('idcv', models.ForeignKey(blank=True, db_column='idcv', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cv')),
                ('idlocalidad', models.ForeignKey(db_column='idLocalidad', on_delete=django.db.models.deletion.CASCADE, to='app.localidad')),
                ('idprofesion', models.ForeignKey(db_column='idProfesion', on_delete=django.db.models.deletion.CASCADE, to='app.profesion')),
            ],
            options={
                'db_table': 'Trabajador',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('idvaloracion', models.AutoField(db_column='idValoracion', primary_key=True, serialize=False)),
                ('estrellas', models.IntegerField()),
                ('opinion', models.TextField(blank=True, null=True)),
                ('idtrabajador', models.ForeignKey(db_column='idTrabajador', on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
            options={
                'db_table': 'Valoracion',
            },
        ),
        migrations.CreateModel(
            name='Trabajadorxprofesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprofesion', models.ForeignKey(blank=True, db_column='idProfesion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profesion')),
                ('idtrabajador', models.ForeignKey(db_column='idTrabajador', on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
            options={
                'db_table': 'TrabajadorxProfesion',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idsolicitud', models.AutoField(db_column='idSolicitud', primary_key=True, serialize=False)),
                ('empresa', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('idtrabajadores', models.ManyToManyField(related_name='Solicitud', to='app.trabajador')),
            ],
            options={
                'db_table': 'Solicitud',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idprovincia', models.AutoField(db_column='idProvincia', primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('idlocalidad', models.ForeignKey(db_column='idLocalidad', on_delete=django.db.models.deletion.CASCADE, to='app.localidad')),
            ],
            options={
                'db_table': 'Provincia',
            },
        ),
    ]
