# Generated by Django 4.2.7 on 2025-01-22 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_trabajador_estadocontrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesion',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='idlocalidad',
        ),
        migrations.AddField(
            model_name='localidad',
            name='idprovincia',
            field=models.ForeignKey(db_column='idprovincia', default=1, on_delete=django.db.models.deletion.CASCADE, to='app.provincia'),
            preserve_default=False,
        ),
    ]
