# Generated by Django 5.1.2 on 2025-01-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_profesion_experiencia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trabajador",
            name="idarchivo",
        ),
        migrations.RemoveField(
            model_name="trabajador",
            name="idcv",
        ),
        migrations.AddField(
            model_name="trabajador",
            name="cvlink",
            field=models.FileField(blank=True, upload_to="cv/"),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="imagenlink",
            field=models.ImageField(blank=True, upload_to="photos/"),
        ),
        migrations.AlterModelTable(
            name="localidad",
            table=None,
        ),
        migrations.DeleteModel(
            name="Archivo",
        ),
        migrations.DeleteModel(
            name="Cv",
        ),
    ]
