# Generated by Django 4.2.7 on 2025-02-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_trabajador_idarchivo_remove_trabajador_idcv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='idtrabajadores',
            field=models.ManyToManyField(related_name='solicitudes', to='app.trabajador'),
        ),
    ]
