# Generated by Django 5.1.2 on 2025-02-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_solicitud_idtrabajadores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trabajador",
            name="dni",
            field=models.IntegerField(db_column="dni"),
        ),
    ]
