# Generated by Django 5.1.2 on 2025-02-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_trabajador_dni"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manga",
                    models.CharField(
                        choices=[("L", "Largo"), ("C", "Corto")], max_length=1
                    ),
                ),
                (
                    "talle",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "db_table": "Pedido",
            },
        ),
    ]
