# Generated by Django 5.1.2 on 2025-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="manga",
            field=models.TextField(choices=[("L", "Largo"), ("C", "Corto")]),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="talle",
            field=models.TextField(
                choices=[
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra-Large"),
                    ("XXL", "Extra-extra-large"),
                ]
            ),
        ),
    ]
