# Generated by Django 5.1.2 on 2025-02-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_pedido_manga_alter_pedido_talle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="manga",
            field=models.TextField(choices=[("largo", "Largo"), ("corto", "Corto")]),
        ),
    ]
