# Generated by Django 5.1.2 on 2025-02-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_pedido_manga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="manga",
            field=models.TextField(choices=[("Largo", "largo"), ("Corto", "corto")]),
        ),
    ]
